services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: m12345678

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: m12345678
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

volumes:
  postgres_data: